In [2]:
import pandas as pd
import os

In [3]:
ess_path = "../data/raw/ESS.csv"

In [4]:
ess_data = pd.read_csv(ess_path)

In [5]:
ess_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530711 entries, 0 to 530710
Data columns (total 42 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   name      530711 non-null  object
 1   essround  530711 non-null  int64
 2   edition   530711 non-null  float64
 3   proddate  530711 non-null  object
 4   idno      530711 non-null  int64
 5   cntry     530711 non-null  object
 6   dweight   530711 non-null  float64
 7   pspwght   530711 non-null  float64
 8   pweight   530711 non-null  float64
 9   anweight  440174 non-null  float64
 10  prob      149360 non-null  float64
 11  stratum   149360 non-null  float64
 12  psu       149360 non-null  float64
 13  netuse    235878 non-null  float64
 14  netusoft  193747 non-null  float64
 15  netustm   193747 non-null  float64
 16  nwspol    193747 non-null  float64
 17  nwsppol   242106 non-null  float64
 18  nwsptot   242106 non-null  float64
 19  pplfair   530711 non-null  int64
 20  pplhlp    530711 non-null  int64
 21  ppltrst   530711 non-null  int64
 22  rdpol     242106 non-null  float64
 23  rdtot     242106 non-null  float64
 24  tvpol     336964 non-null  float64
 25  tvtot     336964 non-null  float64
 26  dmcntov   54673 non-null   float64
 27  polintr   530711 non-null  int64
 28  stfdem    530711 non-null  int64
 29  stflife   530711 non-null  int64
 30  trstep    530711 non-null  int64
 31  trstlgl   530711 non-null  int64
 32  trstplc   530711 non-null  int64
 33  trstplt   530711 non-null  int64
 34  trstprt   488352 non-null  float64
 35  trstun    530711 non-null  int64
 36  trstsci   59685 non-null   float64
 37  loylead   99841 non-null   float64
 38  medcrgv   114358 non-null  float64
 39  medcrgvc  114358 non-null  float64
 40  meprinf   54673 non-null   float64
 41  implvdm   114358 non-null  float64
dtypes: float64(26), int64(13), object(3)
memory usage: 170.1+ MB

In [6]:
html_data = pd.read_html("../data/raw/ESS.html")

In [7]:
ess_data["cntry"].unique()

array(['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'ES', 'FI', 'FR', 'GB', 'GR',
       'HU', 'IE', 'IL', 'IT', 'LU', 'NL', 'NO', 'PL', 'PT', 'SE', 'SI',
       'EE', 'IS', 'SK', 'TR', 'UA', 'BG', 'CY', 'RU', 'HR', 'LV', 'RO',
       'LT', 'AL', 'XK', 'ME', 'RS', 'MK'], dtype=object)

In [9]:
ess_data.head()

,name,essround,edition,proddate,idno,cntry,dweight,pspwght,pweight,anweight,...,trstplc,trstplt,trstprt,trstun,trstsci,loylead,medcrgv,medcrgvc,meprinf,implvdm
0,ESS1e06_7,1,6.7,23.11.2023,1,AT,0.9452,0.940933,0.271487,0.255451,...,10,0,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN
1,ESS1e06_7,1,6.7,23.11.2023,2,AT,0.4726,0.470466,0.271487,0.127726,...,5,0,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN
2,ESS1e06_7,1,6.7,23.11.2023,3,AT,0.9452,1.392155,0.271487,0.377953,...,8,2,NaN,88,NaN,NaN,NaN,NaN,NaN,NaN
3,ESS1e06_7,1,6.7,23.11.2023,4,AT,0.9452,1.382163,0.271487,0.375240,...,9,4,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN
4,ESS1e06_7,1,6.7,23.11.2023,6,AT,1.8905,1.437766,0.271487,0.390336,...,4,4,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
ess_data = ess_data.drop(labels=["name", "essround", "edition", "proddate"], axis=1)

KeyError: "['name', 'essround', 'edition', 'proddate'] not found in axis"

In [14]:
ess_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530711 entries, 0 to 530710
Data columns (total 38 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   idno      530711 non-null  int64
 1   cntry     530711 non-null  object
 2   dweight   530711 non-null  float64
 3   pspwght   530711 non-null  float64
 4   pweight   530711 non-null  float64
 5   anweight  440174 non-null  float64
 6   prob      149360 non-null  float64
 7   stratum   149360 non-null  float64
 8   psu       149360 non-null  float64
 9   netuse    235878 non-null  float64
 10  netusoft  193747 non-null  float64
 11  netustm   193747 non-null  float64
 12  nwspol    193747 non-null  float64
 13  nwsppol   242106 non-null  float64
 14  nwsptot   242106 non-null  float64
 15  pplfair   530711 non-null  int64
 16  pplhlp    530711 non-null  int64
 17  ppltrst   530711 non-null  int64
 18  rdpol     242106 non-null  float64
 19  rdtot     242106 non-null  float64
 20  tvpol     336964 non-null  float64
 21  tvtot     336964 non-null  float64
 22  dmcntov   54673 non-null   float64
 23  polintr   530711 non-null  int64
 24  stfdem    530711 non-null  int64
 25  stflife   530711 non-null  int64
 26  trstep    530711 non-null  int64
 27  trstlgl   530711 non-null  int64
 28  trstplc   530711 non-null  int64
 29  trstplt   530711 non-null  int64
 30  trstprt   488352 non-null  float64
 31  trstun    530711 non-null  int64
 32  trstsci   59685 non-null   float64
 33  loylead   99841 non-null   float64
 34  medcrgv   114358 non-null  float64
 35  medcrgvc  114358 non-null  float64
 36  meprinf   54673 non-null   float64
 37  implvdm   114358 non-null  float64
dtypes: float64(25), int64(12), object(1)
memory usage: 153.9+ MB

looking into the html to find interesting features:

* nwsppol: Newspaper reading, politics/current affairs on average weekday
* pplfair: Most people try to take advantage of you, or try to be fair
* pplhlp: Most of the time people helpful or mostly looking out for themselves
* ppltrst: Most people can be trusted or you can't be too careful
* rdpol: Radio listening, news/politics/current affairs on average weekday
* tvpol: TV watching, news/politics/current affairs on average weekday
* dmcntov: How democratic [country] is overall
* polintr: How interested in politics
* stfdem: How satisfied with the way democracy works in country
* stflife: How satisfied with life as a whole
* trstep: Trust in the European Parliament
* trstlgl: Trust in the legal system
* trstplc: Trust in the police
* trstplt: Trust in politicians
* trstprt: Trust in political parties
* trstsci: Trust in scientists
* loylead: Country needs most loyalty towards its leaders
* medcrgv: The media are free to criticise the government
* medcrgvc: In country the media are free to criticise the government
* meprinf: The media provide citizens with reliable information to judge the government
* implvdm: How important for you to live in democratically governed country

In [ ]:
selected_features = [
    "idno", "cntry", "dweight", "pspwght", "pweight", "anweight", "prob", "stratum", "psu", 'nwsppol', 'pplfair', 'pplhlp', 'ppltrst', 'rdpol', 'tvpol', 'dmcntov', 
    'polintr', 'stfdem', 'stflife', 'trstep', 'trstlgl', 'trstplc', 'trstplt', 
    'trstprt', 'trstsci', 'loylead', 'medcrgv', 'medcrgvc', 'meprinf', 'implvdm'
]

filtered_ess_data = ess_data[selected_features]