In [1]:
import pandas as pd
import os

In [2]:
ess_path = "../data/raw/ESS.csv"

In [5]:
ess_data = pd.read_csv(ess_path)

In [7]:
ess_data.head()

,name,essround,edition,proddate,idno,cntry,dweight,pspwght,pweight,anweight,...,trstplc,trstplt,trstprt,trstun,trstsci,loylead,medcrgv,medcrgvc,meprinf,implvdm
0,ESS1e06_7,1,6.7,23.11.2023,1,AT,0.9452,0.940933,0.271487,0.255451,...,10,0,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN
1,ESS1e06_7,1,6.7,23.11.2023,2,AT,0.4726,0.470466,0.271487,0.127726,...,5,0,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN
2,ESS1e06_7,1,6.7,23.11.2023,3,AT,0.9452,1.392155,0.271487,0.377953,...,8,2,NaN,88,NaN,NaN,NaN,NaN,NaN,NaN
3,ESS1e06_7,1,6.7,23.11.2023,4,AT,0.9452,1.382163,0.271487,0.375240,...,9,4,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN
4,ESS1e06_7,1,6.7,23.11.2023,6,AT,1.8905,1.437766,0.271487,0.390336,...,4,4,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
html_data = pd.read_html("../data/raw/ESS.html")

In [9]:
ess_data["cntry"].unique()

array(['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'ES', 'FI', 'FR', 'GB', 'GR',
       'HU', 'IE', 'IL', 'IT', 'LU', 'NL', 'NO', 'PL', 'PT', 'SE', 'SI',
       'EE', 'IS', 'SK', 'TR', 'UA', 'BG', 'CY', 'RU', 'HR', 'LV', 'RO',
       'LT', 'AL', 'XK', 'ME', 'RS', 'MK'], dtype=object)