In [1]:
import pandas as pd
import numpy as np

world_bank_data = pd.read_csv("../data/raw/world_bank_development_indicators.csv")
countries = pd.read_csv("../data/raw/country_mapping.csv")
print(world_bank_data.head(10))
countries.head()

       country        date  agricultural_land%  forest_land%  land_area  \
0  Afghanistan  1960-01-01                 NaN           NaN        NaN
1  Afghanistan  1961-01-01           57.878356           NaN   652230.0
2  Afghanistan  1962-01-01           57.955016           NaN   652230.0
3  Afghanistan  1963-01-01           58.031676           NaN   652230.0
4  Afghanistan  1964-01-01           58.116002           NaN   652230.0
5  Afghanistan  1965-01-01           58.123668           NaN   652230.0
6  Afghanistan  1966-01-01           58.192662           NaN   652230.0
7  Afghanistan  1967-01-01           58.229459           NaN   652230.0
8  Afghanistan  1968-01-01           58.230992           NaN   652230.0
9  Afghanistan  1969-01-01           58.255523           NaN   652230.0

   avg_precipitation  trade_in_services%  control_of_corruption_estimate  \
0                NaN                 NaN                             NaN
1              327.0                 NaN                             NaN
2              327.0                 NaN                             NaN
3              327.0                 NaN                             NaN
4              327.0                 NaN                             NaN
5              327.0                 NaN                             NaN
6              327.0                 NaN                             NaN
7              327.0                 NaN                             NaN
8              327.0                 NaN                             NaN
9              327.0                 NaN                             NaN

   control_of_corruption_std  access_to_electricity%  ...  \
0                        NaN                     NaN  ...
1                        NaN                     NaN  ...
2                        NaN                     NaN  ...
3                        NaN                     NaN  ...
4                        NaN                     NaN  ...
5                        NaN                     NaN  ...
6                        NaN                     NaN  ...
7                        NaN                     NaN  ...
8                        NaN                     NaN  ...
9                        NaN                     NaN  ...

   multidimensional_poverty_headcount_ratio%  gini_index  birth_rate  \
0                                        NaN         NaN      50.340
1                                        NaN         NaN      50.443
2                                        NaN         NaN      50.570
3                                        NaN         NaN      50.703
4                                        NaN         NaN      50.831
5                                        NaN         NaN      50.872
6                                        NaN         NaN      50.986
7                                        NaN         NaN      51.081
8                                        NaN         NaN      51.148
9                                        NaN         NaN      51.195

   death_rate  life_expectancy_at_birth  population  rural_population  \
0      31.921                    32.535   8622466.0         7898093.0
1      31.349                    33.068   8790140.0         8026804.0
2      30.845                    33.547   8969047.0         8163985.0
3      30.359                    34.016   9157465.0         8308019.0
4      29.867                    34.494   9355514.0         8458694.0
5      29.389                    34.953   9565147.0         8617815.0
6      28.872                    35.453   9783147.0         8782038.0
7      28.396                    35.924  10010030.0         8951970.0
8      27.895                    36.418  10247780.0         9128927.0
9      27.398                    36.910  10494489.0         9311235.0

   voice_and_accountability_estimate  voice_and_accountability_std  \
0                                NaN                           NaN
1                                NaN                           NaN
2                                NaN                           NaN
3                                NaN                           NaN
4                                NaN                           NaN
5                                NaN                           NaN
6                                NaN                           NaN
7                                NaN                           NaN
8                                NaN                           NaN
9                                NaN                           NaN

   intentional_homicides
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
5                    NaN
6                    NaN
7                    NaN
8                    NaN
9                    NaN

[10 rows x 50 columns]

       Country ISO2 Code
0      Albania        AL
1      Austria        AT
2      Belgium        BE
3     Bulgaria        BG
4  Switzerland        CH

In [2]:
world_bank_data.columns

Index(['country', 'date', 'agricultural_land%', 'forest_land%', 'land_area',
       'avg_precipitation', 'trade_in_services%',
       'control_of_corruption_estimate', 'control_of_corruption_std',
       'access_to_electricity%', 'renewvable_energy_consumption%',
       'electric_power_consumption', 'CO2_emisions',
       'other_greenhouse_emisions', 'population_density', 'inflation_annual%',
       'real_interest_rate', 'risk_premium_on_lending',
       'research_and_development_expenditure%', 'central_goverment_debt%',
       'tax_revenue%', 'expense%', 'goverment_effectiveness_estimate',
       'goverment_effectiveness_std', 'human_capital_index', 'doing_business',
       'time_to_get_operation_license', 'statistical_performance_indicators',
       'individuals_using_internet%', 'logistic_performance_index',
       'military_expenditure%', 'GDP_current_US',
       'political_stability_estimate', 'political_stability_std',
       'rule_of_law_estimate', 'rule_of_law_std',
       'regulatory_quality_estimate', 'regulatory_quality_std',
       'government_expenditure_on_education%',
       'government_health_expenditure%',
       'multidimensional_poverty_headcount_ratio%', 'gini_index', 'birth_rate',
       'death_rate', 'life_expectancy_at_birth', 'population',
       'rural_population', 'voice_and_accountability_estimate',
       'voice_and_accountability_std', 'intentional_homicides'],
      dtype='object')

In [3]:
filtered_data = world_bank_data.merge(countries, how='inner', left_on='country', right_on='Country')
filtered_data = filtered_data.drop(columns=['Country', 'ISO2 Code', 'land_area', 'other_greenhouse_emisions', 'real_interest_rate', 'risk_premium_on_lending', 'tax_revenue%', 'goverment_effectiveness_std', 'doing_business', 'time_to_get_operation_license', 'statistical_performance_indicators', 'logistic_performance_index', 'GDP_current_US', 'political_stability_std', 'rule_of_law_std', 'regulatory_quality_std', 'voice_and_accountability_std', 'human_capital_index', 'multidimensional_poverty_headcount_ratio%', 'electric_power_consumption'])
filtered_data['date'] = pd.to_datetime(filtered_data['date'])
filtered_data = filtered_data[
    (filtered_data['date'].dt.year >= 2005) & (filtered_data['date'].dt.year <= 2023)
]
filtered_data.head()

,country,date,agricultural_land%,forest_land%,avg_precipitation,trade_in_services%,control_of_corruption_estimate,control_of_corruption_std,access_to_electricity%,renewvable_energy_consumption%,...,government_expenditure_on_education%,government_health_expenditure%,gini_index,birth_rate,death_rate,life_expectancy_at_birth,population,rural_population,voice_and_accountability_estimate,intentional_homicides
45,Albania,2005-01-01,39.306569,28.309672,1485.0,32.905109,-0.813264,0.160477,99.371124,36.77,...,3.281550,2.665318,30.6,13.235,6.306,76.621,3011487.0,1604189.0,0.003672,5.078094
46,Albania,2006-01-01,40.875912,28.356277,1485.0,36.187926,-0.790545,0.152564,99.389366,31.62,...,3.191460,2.559311,NaN,12.539,6.477,76.816,2992547.0,1561661.0,0.075890,3.163096
47,Albania,2007-01-01,40.839416,28.402883,1485.0,37.734105,-0.706940,0.155251,99.428452,32.00,...,3.275930,2.435714,NaN,12.070,6.318,77.549,2970017.0,1517619.0,0.113008,3.528127
48,Albania,2008-01-01,43.102190,28.449489,1485.0,39.656173,-0.605212,0.144491,100.000000,35.79,...,3.509226,2.271264,30.0,11.868,6.570,77.653,2947314.0,1473922.0,0.174939,3.150738
49,Albania,2009-01-01,43.843066,28.496095,1485.0,40.601399,-0.545271,0.149075,99.554451,37.09,...,NaN,2.338068,NaN,11.841,6.810,77.781,2927519.0,1432259.0,0.141477,2.900488

In [4]:
filtered_data.to_csv("../data/processed/world_bank.csv", index=False, index_label=False)

In [5]:
filtered_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 738 entries, 45 to 2462
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   country                                738 non-null    object
 1   date                                   738 non-null    datetime64[ns]
 2   agricultural_land%                     627 non-null    float64
 3   forest_land%                           627 non-null    float64
 4   avg_precipitation                      560 non-null    float64
 5   trade_in_services%                     677 non-null    float64
 6   control_of_corruption_estimate         684 non-null    float64
 7   control_of_corruption_std              684 non-null    float64
 8   access_to_electricity%                 629 non-null    float64
 9   renewvable_energy_consumption%         592 non-null    float64
 10  CO2_emisions                           592 non-null    float64
 11  population_density                     627 non-null    float64
 12  inflation_annual%                      682 non-null    float64
 13  research_and_development_expenditure%  587 non-null    float64
 14  central_goverment_debt%                332 non-null    float64
 15  expense%                               600 non-null    float64
 16  goverment_effectiveness_estimate       683 non-null    float64
 17  individuals_using_internet%            661 non-null    float64
 18  military_expenditure%                  663 non-null    float64
 19  political_stability_estimate           680 non-null    float64
 20  rule_of_law_estimate                   684 non-null    float64
 21  regulatory_quality_estimate            682 non-null    float64
 22  government_expenditure_on_education%   580 non-null    float64
 23  government_health_expenditure%         591 non-null    float64
 24  gini_index                             595 non-null    float64
 25  birth_rate                             646 non-null    float64
 26  death_rate                             646 non-null    float64
 27  life_expectancy_at_birth               646 non-null    float64
 28  population                             684 non-null    float64
 29  rural_population                       666 non-null    float64
 30  voice_and_accountability_estimate      684 non-null    float64
 31  intentional_homicides                  581 non-null    float64
dtypes: datetime64[ns](1), float64(30), object(1)
memory usage: 190.3+ KB